[project]
name = "xbar-welcome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.1",
    "pycountry>=24.6.1",
    "pydantic-extra-types>=2.10.0",
    "pydantic>=2.9.2",
    "yarl>=1.17.1",
]
